### ISSUE TITLE
Module aliasing for Javascript

### ISSUE THREAD

**Issue by aryx** [returntocorp/semgrep#285]
@aryx 
Took some time to rethink your comment and try different code examples.

I agree with you, it would be way more practical to specify the module.
I broke down possible module import examples to this list:

```javascript
/**/
let foo = require('./foo');
foo.something('yo');

/**/
let fooSome = require('./foo').something;
fooSome('yo1');

/**/
import * as foo1 from './foo';
foo1.something('yo2')

/**/
import {something} from './foo';
something('yo3')

/**/
import foofoo from "./foo";
foofoo.something('yo4')

/**/
import { something as smth } from "./foo";
smth('yo5')

/**/
import("./foo").then(foo2 => {
  foo2.something('yo6');
})

/**/
(async function() {
  const foo3 = await import('./foo');
  foo3.something('yo7')
})()
```
and here is how the rule to catch em all would look like: 
```yaml
rules:
  - id: imports
    patterns:
        - pattern-either:
            - pattern: |
                import $X from "./foo";
                $X.something(...);
            - pattern: |
                $E = require("./foo");
                $E.something(...);
    message: "imports test"
    languages: [javascript]
    severity: ERROR
```

so the basic idea is to specify the exact module path
```
import $X from "./foo";
```
but have all the aliasing handled
```
$X.something(...);
```

_Originally posted by @inkz in https://github.com/returntocorp/sgrep/issues/197#issuecomment-596828741_
