### ISSUE TITLE
semgrep.dev bug: Rule javascript.express.security.audit.xss.mustache.explicit-unescape on non-mustache 

### ISSUE THREAD

**Issue by sonjaq** [returntocorp/semgrep#3344]
https://semgrep.dev/s/B45R?registry=javascript.express.security.audit.xss.mustache.explicit-unescape.template-explicit-unescape

Within an angular project, powered by ionic, my project flagged the following design pattern:

```html
    <ion-input
      color="{{
        form.controls.firstName.invalid && form.controls.firstName.touched
          ? 'danger'
          : inputColor
      }}"
      formControlName="firstName"
      maxlength="42"
    ></ion-input>
 ```  
 
Expected:
javascript.express.security.audit.xss.mustache.explicit-unescape.template-explicit-unescape should not trigger on this pattern, which is popular in our Angular codebases.

From using the semgrep.dev web tool, I found the following update appeared to satisfy my use case and the current sample.

From:
```yaml
    pattern-either:
      - pattern-regex: "{{{((?!include).)*?}}}"
      - pattern-regex: "{{[^}]*&[^}]*}}"
```    

To:
```yaml
    pattern-either:
      - pattern-regex: "{{{((?!include).)*?}}}"
      - pattern-regex: "{{[^}&]*&[^}&]*}}"
```
