### ISSUE TITLE
Leverage equivalences in `semgrep`

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/semgrep#363]
**Is your feature request related to a problem? Please describe.**
`sgrep` recently adds equivalences (see #362). These would allow us to drastically reduce the amount of patterns necessary to write some rules (see, e.g., https://github.com/returntocorp/sgrep-rules/pull/290).

**Describe the solution you'd like**
Let's leverage this new functionality in `sgrep-lint`. One suggestion would be to simply add an `equivalences` section in the check YAML file.

**Comment by nbrahms** [comment]
Closes #176

**Comment by minusworld** [comment]
Proposal:
```yaml
rules:
  - id: whatever
    pattern: $X == $Y
    equivalences: 
      - pattern: $X == $Y <==> $Y == $X
      - pattern: $X == $Y ==> $X != $Y
    message: ""
    severity: WARNING
    languages: [python, c, java, javascript]
```

**Comment by brendongo** [comment]
Looks reasonable. Do they have to be prefixed with `- pattern:` ?

**Comment by minusworld** [comment]
> Looks reasonable. Do they have to be prefixed with `- pattern:` ?

I figured it would match how `patterns` works currently, which also requires `pattern` or similar.

It also sort-of-matches the YAML file that semgrep-core expects:

```yaml
equivalences:
  - id: plus-commutative
    pattern: $X + $Y <==> $Y + $X
    languages: [python, javascript, c, go, java]
  - id: eq-to-no-eq
    pattern: $X == $X ==> $X != $X
    languages: [python, javascript, c, go, java]
```

**Comment by nbrahms** [comment]
Can I suggest using a different keyword than `pattern`; just because the grammar is different, I think we should use a different label.

**Comment by nbrahms** [comment]
Alternatively, we could write something like:
```yaml
- equivalences:
  - id: plus-commutative
    type: bijective
    left-pattern: $X + $Y
    right-pattern: $Y + $X
  - id: eq-to-no-eq:
    type: injective
    left-pattern: $X == $X
    right-pattern: $X != $X
```

I'm not too enthusiastic about using things like `bijective` and `injective`, but not sure what else we would call them...
