### ISSUE TITLE
open-not-closed rule False Positive

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/semgrep#894]
https://semgrep.live/nJWG

```yaml
rules:
  - id: open-never-closed
    patterns:
      - pattern: $FILE = open(...)
      - pattern-not-inside: |
          $FILE = open(...)
          ...
          $FILE.close()
    message: "file object opened without corresponding close"
    languages: [python]
    severity: ERROR
```

Fails to detect `file.txt` below:

```py
f = open("file.txt")
f.read()
f = open("file2.txt")
f.read()
f.close()
```
